version: 2.1

parameters:
  private_key:
    type: string
    default: ""

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Setup SSH Key
          command: |
            mkdir -p ~/.ssh
            echo "<< pipeline.parameters.private_key >>" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy Application
          command: |
            echo "Deploying application..."
            # Add deployment commands here

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy:
          private_key: "your_private_key_here"
